# Generated by Django 6.0.4 on 2026-04-25 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('envios', '0001_initial'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Activo'), (9, 'De baja')], default=1)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['apellidos'],
            },
        ),
        migrations.AlterModelOptions(
            name='encomienda',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Encomienda', 'verbose_name_plural': 'Encomiendas'},
        ),
        migrations.RenameField(
            model_name='encomienda',
            old_name='fecha_envio',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='encomienda',
            name='fecha_entrega',
        ),
        migrations.AddField(
            model_name='encomienda',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_destinatario', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='fecha_entrega_est',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='fecha_entrega_real',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='remitente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios_como_remitente', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas', to='rutas.ruta'),
        ),
        migrations.AddField(
            model_name='encomienda',
            name='volumen_cm3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='encomienda',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], default='PE', max_length=2),
        ),
        migrations.AlterModelTable(
            name='encomienda',
            table='encomiendas',
        ),
        migrations.AddField(
            model_name='encomienda',
            name='empleado_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='encomiendas_registradas', to='envios.empleado'),
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], max_length=2)),
                ('estado_nuevo', models.CharField(choices=[('PE', 'Pendiente'), ('TR', 'En tránsito'), ('DE', 'En destino'), ('EN', 'Entregado'), ('DV', 'Devuelto')], max_length=2)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado', to='envios.empleado')),
                ('encomienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='envios.encomienda')),
            ],
            options={
                'db_table': 'historial_estados',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
