# Generated by Django 6.0.4 on 2026-04-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_empleado_alter_encomienda_options_and_more'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='rutas_asignadas',
            field=models.ManyToManyField(blank=True, related_name='empleados_asignados', to='rutas.ruta'),
        ),
    ]
